name: mpg123-core # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Snapping mpg123 for demo purposes on Ubuntu Core
description: |
  mpg123 is an application available in the Ubuntu archive. All I did is to snap it.
  But since Ubuntu Core does not ship with ALSA, I also included some ALSA utilities
  such as speaker-test and aplay.

  INTERFACES THAT NEED CONNECTING
  
  Please keep in mind that Ubuntu Core installs snaps in strict confinement mode by default.
  This means you need to connect interfaces.
  Here's what I am now seeing on my RaspPI:

  skidooman@ubuntu:~$ sudo snap connections mpg123-core
  Interface     Plug                      Slot           Notes
  alsa          mpg123-core:alsa          :alsa          manual
  home          mpg123-core:home          :home          manual
  network       mpg123-core:network       :network       -
  network-bind  mpg123-core:network-bind  :network-bind  -

  The network and network-bind interfaces should be connected automatically. 
  However, alsa and home will need to be connected.
  In order to do so, on your Ubuntu Core, at command line, type
  sudo snap connect mpg123-core:alsa 
  And the same thing for home

  OUTPUT SELECTION

  Not done yet.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  home:
    read: all

apps:
  mpg123:
    command: usr/bin/mpg123.bin
    environment:
      MPG123_MODDIR: $SNAP/usr/lib/aarch64-linux-gnu/mpg123
    plugs: [alsa, home]
  pacmd:
    command: usr/bin/pacmd
    plugs: [alsa, home]
  pulseaudio:
    command: usr/bin/pulseaudio
    plugs: [alsa, home]
  aplay:
    command: usr/bin/aplay
    plugs: [alsa, home]
  speaker-test:
    command: usr/bin/speaker-test
    plugs: [alsa, home]
  jukebox:
    daemon: simple
    restart-condition: on-failure
    command: bin/python3 $SNAP/bin/jukebox.py
    plugs: [alsa, network, network-bind]
    environment: 
      PYTHONPATH: $SNAP/lib/python3.8/site-packages
      MPG123_MODDIR: $SNAP/usr/lib/aarch64-linux-gnu/mpg123
  #jackd-daemon:
  #  command: usr/bin/jackd -R -dalsa
  #  daemon: simple

parts:
  player:
    # See 'snapcraft plugins'
    plugin: nil
    stage-packages:
      #- libasound2
      #- libaudio2
      #- libc6
      #- libjack-jackd2-0
      #- libmpg123-0
      #- libopenal1
      #- libout123-0
      #- libportaudio2
      #- libpulse0
      - mpg123
  alsa:
    plugin: nil
    stage-packages:
      - alsa-base
      - alsa-utils
      - libasound2
      - libasound2-data
      - libasound2-plugins
  pulseaudio:
    plugin: nil
    stage-packages:
      - pulseaudio
  jukebox:
    plugin: python
    source: ./jukebox
    python-packages: [flask]
    override-prime: |
      craftctl default
      cp "${CRAFT_PART_SRC}/jukebox.py" "${CRAFT_PRIME}/bin/jukebox.py"
  #jackd:
  #  plugin: nil
  #  stage-packages:
  #    - jackd
  #etcfile:
  #  plugin: dump
  #  source: etcfile

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  #/usr/share/alsa:
  #  symlink: $SNAP/usr/share/alsa
  /usr/lib/aarch64-linux-gnu/pulseaudio:
    bind: $SNAP/usr/lib/aarch64-linux-gnu/pulseaudio
  /etc/asound.conf:
    symlink: $SNAP/etc/asound.conf
