name: mpg123-core # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Snap encompassing mpg123 simple program for Ubuntu Core usage
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  home:
    read: all

apps:
  mpg123:
    command: usr/bin/mpg123.bin
    environment:
      MPG123_MODDIR: $SNAP/usr/lib/aarch64-linux-gnu/mpg123
    plugs: [alsa, home]
  pacmd:
    command: usr/bin/pacmd
    plugs: [alsa, home]
  pulseaudio:
    command: usr/bin/pulseaudio
    plugs: [alsa, home]
  aplay:
    command: usr/bin/aplay
    plugs: [alsa, home]
  speaker-test:
    command: usr/bin/speaker-test
    plugs: [alsa, home]
  #jackd-daemon:
  #  command: usr/bin/jackd -R -dalsa
  #  daemon: simple

parts:
  player:
    # See 'snapcraft plugins'
    plugin: nil
    stage-packages:
      #- libasound2
      #- libaudio2
      #- libc6
      #- libjack-jackd2-0
      #- libmpg123-0
      #- libopenal1
      #- libout123-0
      #- libportaudio2
      #- libpulse0
      - mpg123
  alsa:
    plugin: nil
    stage-packages:
      - alsa-base
      - alsa-utils
      - libasound2
      - libasound2-data
      - libasound2-plugins
  pulseaudio:
    plugin: nil
    stage-packages:
      - pulseaudio
  #jackd:
  #  plugin: nil
  #  stage-packages:
  #    - jackd
  etcfile:
    plugin: dump
    source: etcfile

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  #/usr/share/alsa:
  #  symlink: $SNAP/usr/share/alsa
  /usr/lib/aarch64-linux-gnu/pulseaudio:
    bind: $SNAP/usr/lib/aarch64-linux-gnu/pulseaudio
  /etc/asound.conf:
    symlink: $SNAP/etc/asound.conf
